package org.geoint.acetate.api;

import java.util.Collection;
import java.util.ServiceLoader;
import org.geoint.acetate.domain.model.ObjectModel;
import org.geoint.acetate.meta.annotation.MetaObject;

/**
 * Objects which process matching {@link MetaObject}.
 *
 * Frameworks may define any number of MetaModelProcessors which are notified 
 * Instances of MetaModelProcessor are loaded through the {@link ServiceLoader}.
 *
 * @param <M> type of metamodel generated by this processor
 */
public interface MetaModelProcessor<M extends MetaObject> {

    /**
     * Supported meta model name.
     *
     * @return model name this processor supports
     */
    String supportedModel();

    /**
     * Supported metamodel version.
     *
     * @return supported metamodel version
     */
    String supportedVersion();

    /**
     * Processes the object models into a meta model.
     *
     * @param modelComponents
     * @return meta model
     */
    M model(Collection<ObjectModel> modelComponents);

}
