package org.geoint.acetate.spi;

import java.util.Collection;
import java.util.ServiceLoader;
import org.geoint.acetate.meta.model.MetaModel;
import org.geoint.acetate.meta.model.ObjectModel;

/**
 * Processes a {@link MetaModel}.
 *
 * Instances of ModelProcessor are loaded through the {@link ServiceLoader}.
 *
 * @param <M> type of metamodel generated by this processor
 */
public interface ModelProcessor<M extends MetaModel> {

    /**
     * Supported meta model name.
     *
     * @return model name this processor supports
     */
    String supportedModel();

    /**
     * Supported metamodel version.
     *
     * @return supported metamodel version
     */
    String supportedVersion();

    /**
     * Processes the object models into a meta model.
     *
     * @param modelComponents
     * @return meta model
     */
    M model(Collection<ObjectModel> modelComponents);

}
